services:
  app:
    build: .
    container_name: file_server_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: file_server
      DB_USER: file_user
      DB_PASSWORD: file_password

  db:
    image: postgres:16
    container_name: file_server_db
    restart: always
    environment:
      POSTGRES_DB: file_server
      POSTGRES_USER: file_user
      POSTGRES_PASSWORD: file_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: